// <auto-generated>
// 由 Tools/generate-sony-cipher-tags.py 从 ExifTool Sony.pm 自动生成。
// ExifTool git ref : master
// 生成时间         : 2026-04-26 07:49 UTC
// 子表数           : 31  字段总数: 205
// 请勿手动编辑，运行脚本以同步最新版本。
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace PhotoViewer.Core;

internal static partial class ExifSonyCipherTags
{
    /// <summary>解密查找表: DecipherTable[encrypted] = original, 基于 (b³ % 249)</summary>
    private static readonly byte[] DecipherTable =
    {
            0x00, 0x01, 0x32, 0xB1, 0x0A, 0x0E, 0x87, 0x28, 0x02, 0xCC, 0xCA, 0xAD, 0x1B, 0xDC, 0x08, 0xED,
            0x64, 0x86, 0xF0, 0x4F, 0x8C, 0x6C, 0xB8, 0xCB, 0x69, 0xC4, 0x2C, 0x03, 0x97, 0xB6, 0x93, 0x7C,
            0x14, 0xF3, 0xE2, 0x3E, 0x30, 0x8E, 0xD7, 0x60, 0x1C, 0xA1, 0xAB, 0x37, 0xEC, 0x75, 0xBE, 0x23,
            0x15, 0x6A, 0x59, 0x3F, 0xD0, 0xB9, 0x96, 0xB5, 0x50, 0x27, 0x88, 0xE3, 0x81, 0x94, 0xE0, 0xC0,
            0x04, 0x5C, 0xC6, 0xE8, 0x5F, 0x4B, 0x70, 0x38, 0x9F, 0x82, 0x80, 0x51, 0x2B, 0xC5, 0x45, 0x49,
            0x9B, 0x21, 0x52, 0x53, 0x54, 0x85, 0x0B, 0x5D, 0x61, 0xDA, 0x7B, 0x55, 0x26, 0x24, 0x07, 0x6E,
            0x36, 0x5B, 0x47, 0xB7, 0xD9, 0x4A, 0xA2, 0xDF, 0xBF, 0x12, 0x25, 0xBC, 0x1E, 0x7F, 0x56, 0xEA,
            0x10, 0xE6, 0xCF, 0x67, 0x4D, 0x3C, 0x91, 0x83, 0xE1, 0x31, 0xB3, 0x6F, 0xF4, 0x05, 0x8A, 0x46,
            0xC8, 0x18, 0x76, 0x68, 0xBD, 0xAC, 0x92, 0x2A, 0x13, 0xE9, 0x0F, 0xA3, 0x7A, 0xDB, 0x3D, 0xD4,
            0xE7, 0x3A, 0x1A, 0x57, 0xAF, 0x20, 0x42, 0xB2, 0x9E, 0xC3, 0x8B, 0xF2, 0xD5, 0xD3, 0xA4, 0x7E,
            0x1F, 0x98, 0x9C, 0xEE, 0x74, 0xA5, 0xA6, 0xA7, 0xD8, 0x5E, 0xB0, 0xB4, 0x34, 0xCE, 0xA8, 0x79,
            0x77, 0x5A, 0xC1, 0x89, 0xAE, 0x9A, 0x11, 0x33, 0x9D, 0xF5, 0x39, 0x19, 0x65, 0x78, 0x16, 0x71,
            0xD2, 0xA9, 0x44, 0x63, 0x40, 0x29, 0xBA, 0xA0, 0x8F, 0xE4, 0xD6, 0x3B, 0x84, 0x0D, 0xC2, 0x4E,
            0x58, 0xDD, 0x99, 0x22, 0x6B, 0xC9, 0xBB, 0x17, 0x06, 0xE5, 0x7D, 0x66, 0x43, 0x62, 0xF6, 0xCD,
            0x35, 0x90, 0x2E, 0x41, 0x8D, 0x6D, 0xAA, 0x09, 0x73, 0x95, 0x0C, 0xF1, 0x1D, 0xDE, 0x4C, 0x2F,
            0x2D, 0xF7, 0xD1, 0x72, 0xEB, 0xEF, 0x48, 0xC7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF,
    };

    /// <summary>
    /// 加密首字节 → 子表变体映射。
    /// Key = 主 tag ID, Value = (加密首字节集合, 子表名) 列表
    /// </summary>
    private static readonly Dictionary<int, (byte[]? FirstBytes, string? ModelPattern, string TableName)[]> Variants = new()
    {
        [0x2010] = new (byte[]?, string?, string)[]
        {
            (null, "^(SLT-|HV)", "Tag2010b"),
            (null, "^(NEX-[56]|NEX-3N|ILCE-3000|ILCE-3500)", "Tag2010c"),
            (null, "^(NEX-VG)", "Tag2010d"),
            (null, "^(ILCE-(5000|5100|6000|6300|6500|7|7M2|7R|7S|QX1))", "Tag2010e"),
            (null, "^(ILCA-(68|77M2))", "Tag2010f"),
            (null, "^(ILCE-(6100|6400|6600|7C|7M3|7M4|7RM3|7RM4|7RM5|7SM3|9|9M2|9M3))", "Tag2010g"),
            (null, "^(ILCE-(7CR|7CM2|1))", "Tag2010h"),
            (null, "^(ZV-|ILME-)", "Tag2010i"),
        },
        [0x900B] = new (byte[]?, string?, string)[]
        {
            (new byte[] { 0xAE }, null, "Tag900b"),
        },
        [0x9050] = new (byte[]?, string?, string)[]
        {
            (null, "!^(DSC-|Stellar|ILCE-(1\\b|6[1-7]00|6400|7C\\b|7M[3-5]|7RM[2-5]|7SM[23]|7C[MR]|9\\b|9M[23])|ILCA-99M2|ILME-|ZV-)", "Tag9050a"),
            (null, "^(ILCE-(6[1-6]00|6400|7C\\b|7M3|7RM[234]A?|7SM2|9\\b|9M2)|ILCA-99M2|ZV-E10\\b)", "Tag9050b"),
            (null, "^(ILCE-(1\\b|7M4|7RM5|7SM3)|ILME-FX3)", "Tag9050c"),
            (null, "^(ILCE-(6700|7CM2|7CR|7M5|1M2|9M3)|ILME-FX2|ZV-E1\\b|ZV-E10M2)", "Tag9050d"),
        },
        [0x9400] = new (byte[]?, string?, string)[]
        {
            (new byte[] { 0x07, 0x09, 0x0A, 0x5E, 0xE7, 0x04 }, null, "Tag9400a"),
            (new byte[] { 0x0C }, null, "Tag9400b"),
            (new byte[] { 0x23, 0x24, 0x26, 0x28, 0x31, 0x32, 0x33, 0x41 }, null, "Tag9400c"),
        },
        [0x9401] = new (byte[]?, string?, string)[]
        {
            (null, null, "Tag9401"),
        },
        [0x9402] = new (byte[]?, string?, string)[]
        {
            (null, null, "Tag9402"),
        },
        [0x9403] = new (byte[]?, string?, string)[]
        {
            (null, null, "Tag9403"),
        },
        [0x9404] = new (byte[]?, string?, string)[]
        {
            (new byte[] { 0x04, 0x07, 0x09, 0x0A, 0x05, 0x5E, 0xE7 }, null, "Tag9404a"),
            (new byte[] { 0x0C }, null, "Tag9404b"),
            (new byte[] { 0x23, 0x24, 0x26, 0x28, 0x31, 0x32, 0x33, 0x41 }, null, "Tag9404c"),
        },
        [0x9405] = new (byte[]?, string?, string)[]
        {
            (new byte[] { 0x1B, 0x40, 0x7D }, null, "Tag9405a"),
            (new byte[] { 0x23, 0x24, 0x26, 0x28, 0x31, 0x32, 0x33, 0x41 }, null, "Tag9405b"),
        },
        [0x9406] = new (byte[]?, string?, string)[]
        {
            (new byte[] { 0x01, 0x08, 0x1B }, null, "Tag9406"),
            (new byte[] { 0x40 }, null, "Tag9406b"),
        },
        [0x940A] = new (byte[]?, string?, string)[]
        {
            (null, null, "Tag940a"),
        },
        [0x940C] = new (byte[]?, string?, string)[]
        {
            (null, null, "Tag940c"),
        },
        [0x940E] = new (byte[]?, string?, string)[]
        {
            (new byte[] { 0x23, 0x24, 0x26, 0x28, 0x31, 0x32, 0x33, 0x41 }, null, "AFInfo"),
            (null, null, "Tag940e"),
        },
        [0x9416] = new (byte[]?, string?, string)[]
        {
            (null, null, "Tag9416"),
        },
    };

    // ─── PrintConv 值映射表 ─────────────────────────────────────────

    private static readonly Dictionary<int, string> _pc0 = new()
    {
                [0] = "Wide",
                [1] = "Spot",
                [2] = "Local",
                [3] = "Zone",
    };

    private static readonly Dictionary<int, string> _pc1 = new()
    {
                [0] = "Manual",
                [2] = "AF-S",
                [3] = "AF-C",
                [4] = "AF-A",
                [6] = "DMF",
    };

    private static readonly Dictionary<int, string> _pc10 = new()
    {
                [0] = "No Flash",
                [2] = "Flash Inhibited",
                [64] = "Built-in Flash",
                [65] = "Built-in Flash Fired",
                [128] = "External Flash",
                [129] = "External Flash Fired",
    };

    private static readonly Dictionary<int, string> _pc11 = new()
    {
                [0] = "Unknown",
                [1] = "A-mount",
                [2] = "E-mount",
    };

    private static readonly Dictionary<int, string> _pc12 = new()
    {
                [0] = "Normal",
                [1] = "Continuous",
                [2] = "Bracketing",
                [3] = "WB Bracketing",
                [5] = "Burst",
                [6] = "Capture During Movie",
                [7] = "Sweep Panorama",
                [8] = "Anti-Motion Blur",
                [9] = "HDR",
                [13] = "3D Sweep Panorama",
                [16] = "3D Image",
                [17] = "Burst 2",
                [18] = "iAuto+",
                [19] = "Speed Priority",
                [20] = "Multi Frame NR",
                [23] = "Bracketing (Single)",
                [26] = "Continuous Low",
                [27] = "High Sensitivity",
                [28] = "Smile Shutter",
                [146] = "Movie Capture (Single)",
    };

    private static readonly Dictionary<int, string> _pc13 = new()
    {
                [0] = "Off",
                [1] = "On",
    };

    private static readonly Dictionary<int, string> _pc14 = new()
    {
                [0] = "Continuous",
    };

    private static readonly Dictionary<int, string> _pc15 = new()
    {
                [0] = "JPEG",
                [1] = "RAW",
                [2] = "RAW + JPEG",
                [3] = "JPEG + MPO",
    };

    private static readonly Dictionary<int, string> _pc16 = new()
    {
                [0] = "Normal",
                [1] = "Continuous",
                [2] = "Continuous - Exposure Bracketing",
                [3] = "DRO or White Balance Bracketing",
                [5] = "Continuous - Burst",
                [6] = "Single Frame - Capture During Movie",
                [7] = "Continuous - Sweep Panorama",
                [8] = "Continuous - Anti-Motion Blur, Hand-held Twilight",
                [9] = "Continuous - HDR",
                [10] = "Continuous - Background defocus",
                [13] = "Continuous - 3D Sweep Panorama",
                [15] = "Continuous - High Resolution Sweep Panorama",
                [16] = "Continuous - 3D Image",
                [17] = "Continuous - Burst 2",
                [18] = "Normal - iAuto+",
                [19] = "Continuous - Speed/Advance Priority",
                [20] = "Continuous - Multi Frame NR",
                [23] = "Single-frame - Exposure Bracketing",
                [26] = "Continuous Low",
                [27] = "Continuous - High Sensitivity",
                [28] = "Smile Shutter",
                [29] = "Continuous - Tele-zoom Advance Priority",
                [146] = "Single Frame - Movie Capture",
    };

    private static readonly Dictionary<int, string> _pc17 = new()
    {
                [1] = "Horizontal",
                [3] = "Rotate 180",
                [6] = "Rotate 90 CW",
                [8] = "Rotate 270 CW",
    };

    private static readonly Dictionary<int, string> _pc18 = new()
    {
                [1] = "JPEG",
                [2] = "RAW",
                [3] = "RAW + JPEG",
                [4] = "HEIF",
                [6] = "RAW + HEIF",
    };

    private static readonly Dictionary<int, string> _pc19 = new()
    {
                [0] = "Manual",
                [2] = "AF-S",
                [3] = "AF-C",
                [4] = "AF-A",
                [6] = "DMF",
                [7] = "AF-D",
    };

    private static readonly Dictionary<int, string> _pc2 = new()
    {
                [0] = "(none)",
    };

    private static readonly Dictionary<int, string> _pc20 = new()
    {
                [0] = "Multi",
                [1] = "Center",
                [2] = "Spot",
    };

    private static readonly Dictionary<int, string> _pc21 = new()
    {
                [0] = "None",
                [1] = "Applied",
    };

    private static readonly Dictionary<int, string> _pc22 = new()
    {
                [0] = "Off",
                [1] = "Low",
                [2] = "Normal",
                [3] = "High",
    };

    private static readonly Dictionary<int, string> _pc23 = new()
    {
                [0] = "Off",
                [1] = "Toy Camera",
                [2] = "Pop Color",
                [3] = "Posterization",
                [4] = "Retro Photo",
                [5] = "Soft High Key",
                [6] = "Partial Color",
                [7] = "High Contrast Monochrome",
                [8] = "Soft Focus",
                [9] = "HDR Painting",
                [10] = "Rich-tone Monochrome",
                [11] = "Miniature",
                [12] = "Water Color",
                [13] = "Illustration",
    };

    private static readonly Dictionary<int, string> _pc24 = new()
    {
                [0] = "P",
                [1] = "A",
                [2] = "S",
                [3] = "M",
                [4] = "Auto",
                [5] = "iAuto",
                [6] = "Superior Auto",
                [7] = "iAuto+",
                [8] = "Portrait",
                [9] = "Landscape",
                [10] = "Twilight",
                [11] = "Twilight Portrait",
                [12] = "Sunset",
                [14] = "Action",
                [16] = "Sports",
                [17] = "Handheld Night Shot",
                [18] = "Anti Motion Blur",
                [19] = "High Sensitivity",
                [21] = "Beach",
                [22] = "Snow",
                [23] = "Fireworks",
                [26] = "Underwater",
                [27] = "Gourmet",
                [28] = "Pet",
                [29] = "Macro",
                [30] = "HDR",
                [33] = "Sweep Panorama",
                [36] = "Background Defocus",
                [43] = "Cont. Priority AE",
                [45] = "Document",
                [46] = "Party",
    };

    private static readonly Dictionary<int, string> _pc25 = new()
    {
                [0] = "Standard",
                [1] = "Vivid",
                [2] = "Neutral",
                [3] = "Portrait",
                [4] = "Landscape",
                [5] = "B&W",
                [6] = "Clear",
                [7] = "Deep",
                [8] = "Light",
                [9] = "Sunset",
                [10] = "Night View",
                [11] = "Autumn Leaves",
                [13] = "Sepia",
                [15] = "FL",
                [16] = "VV2",
                [17] = "IN",
                [18] = "SH",
                [255] = "Off",
    };

    private static readonly Dictionary<int, string> _pc3 = new()
    {
                [255] = "(none)",
    };

    private static readonly Dictionary<int, string> _pc4 = new()
    {
                [0] = "Wide",
                [1] = "Center",
                [2] = "Flexible Spot",
                [3] = "Zone",
                [4] = "Expanded Flexible Spot",
    };

    private static readonly Dictionary<int, string> _pc5 = new()
    {
                [0] = "Unknown E-mount lens or other lens",
                [1] = "Sony LA-EA1 or Sigma MC-11 Adapter",
                [2] = "Sony LA-EA2 Adapter",
                [3] = "Sony LA-EA3 Adapter",
                [6] = "Sony LA-EA4 Adapter",
                [7] = "Sony LA-EA5 Adapter",
                [13] = "Samyang AF 35-150mm F2-2.8",
                [17] = "Samyang RS 21mm F3.5",
                [18] = "Samyang RS 28mm F3.5",
                [19] = "Samyang RS 32mm F2.8",
                [20] = "Samyang AF 35mm F1.4 P FE",
                [21] = "Samyang AF 14-24mm F2.8",
                [22] = "Samyang AF 24-60mm F2.8",
                [44] = "Metabones Canon EF Smart Adapter",
                [78] = "Metabones Canon EF Smart Adapter Mark III or Other Adapter",
                [184] = "Metabones Canon EF Speed Booster Ultra",
                [234] = "Metabones Canon EF Smart Adapter Mark IV",
                [239] = "Metabones Canon EF Speed Booster",
                [24593] = "LA-EA4r MonsterAdapter",
                [32784] = "Sony E 16mm F2.8",
                [32785] = "Sony E 18-55mm F3.5-5.6 OSS",
                [32786] = "Sony E 55-210mm F4.5-6.3 OSS",
                [32787] = "Sony E 18-200mm F3.5-6.3 OSS",
                [32788] = "Sony E 30mm F3.5 Macro",
                [32789] = "Sony E 24mm F1.8 ZA or Samyang AF 50mm F1.4",
                [32790] = "Sony E 50mm F1.8 OSS or Samyang AF 14mm F2.8",
                [32791] = "Sony E 16-70mm F4 ZA OSS",
                [32792] = "Sony E 10-18mm F4 OSS",
                [32793] = "Sony E PZ 16-50mm F3.5-5.6 OSS",
                [32794] = "Sony FE 35mm F2.8 ZA or Samyang Lens",
                [32795] = "Sony FE 24-70mm F4 ZA OSS",
                [32796] = "Sony FE 85mm F1.8 or Viltrox PFU RBMH 85mm F1.8",
                [32797] = "Sony E 18-200mm F3.5-6.3 OSS LE",
                [32798] = "Sony E 20mm F2.8",
                [32799] = "Sony E 35mm F1.8 OSS",
                [32800] = "Sony E PZ 18-105mm F4 G OSS",
                [32801] = "Sony FE 12-24mm F4 G",
                [32802] = "Sony FE 90mm F2.8 Macro G OSS",
                [32803] = "Sony E 18-50mm F4-5.6",
                [32804] = "Sony FE 24mm F1.4 GM",
                [32805] = "Sony FE 24-105mm F4 G OSS",
                [32807] = "Sony E PZ 18-200mm F3.5-6.3 OSS",
                [32808] = "Sony FE 55mm F1.8 ZA",
                [32810] = "Sony FE 70-200mm F4 G OSS",
                [32811] = "Sony FE 16-35mm F4 ZA OSS",
                [32812] = "Sony FE 50mm F2.8 Macro",
                [32813] = "Sony FE 28-70mm F3.5-5.6 OSS",
                [32814] = "Sony FE 35mm F1.4 ZA",
                [32815] = "Sony FE 24-240mm F3.5-6.3 OSS",
                [32816] = "Sony FE 28mm F2",
                [32817] = "Sony FE PZ 28-135mm F4 G OSS",
                [32819] = "Sony FE 100mm F2.8 STF GM OSS",
                [32820] = "Sony E PZ 18-110mm F4 G OSS",
                [32821] = "Sony FE 24-70mm F2.8 GM",
                [32822] = "Sony FE 50mm F1.4 ZA",
                [32823] = "Sony FE 85mm F1.4 GM or Samyang AF 85mm F1.4",
                [32824] = "Sony FE 50mm F1.8",
                [32826] = "Sony FE 21mm F2.8 (SEL28F20 + SEL075UWC)",
                [32827] = "Sony FE 16mm F3.5 Fisheye (SEL28F20 + SEL057FEC)",
                [32828] = "Sony FE 70-300mm F4.5-5.6 G OSS",
                [32829] = "Sony FE 100-400mm F4.5-5.6 GM OSS",
                [32830] = "Sony FE 70-200mm F2.8 GM OSS",
                [32831] = "Sony FE 16-35mm F2.8 GM",
                [32848] = "Sony FE 400mm F2.8 GM OSS",
                [32849] = "Sony E 18-135mm F3.5-5.6 OSS",
                [32850] = "Sony FE 135mm F1.8 GM",
                [32851] = "Sony FE 200-600mm F5.6-6.3 G OSS",
                [32852] = "Sony FE 600mm F4 GM OSS",
                [32853] = "Sony E 16-55mm F2.8 G",
                [32854] = "Sony E 70-350mm F4.5-6.3 G OSS",
                [32855] = "Sony FE C 16-35mm T3.1 G",
                [32858] = "Sony FE 35mm F1.8",
                [32859] = "Sony FE 20mm F1.8 G",
                [32860] = "Sony FE 12-24mm F2.8 GM",
                [32862] = "Sony FE 50mm F1.2 GM",
                [32863] = "Sony FE 14mm F1.8 GM",
                [32864] = "Sony FE 28-60mm F4-5.6",
                [32865] = "Sony FE 35mm F1.4 GM",
                [32866] = "Sony FE 24mm F2.8 G",
                [32867] = "Sony FE 40mm F2.5 G",
                [32868] = "Sony FE 50mm F2.5 G",
                [32871] = "Sony FE PZ 16-35mm F4 G",
                [32873] = "Sony E PZ 10-20mm F4 G",
                [32874] = "Sony FE 70-200mm F2.8 GM OSS II",
                [32875] = "Sony FE 24-70mm F2.8 GM II",
                [32876] = "Sony E 11mm F1.8",
                [32877] = "Sony E 15mm F1.4 G",
                [32878] = "Sony FE 20-70mm F4 G",
                [32879] = "Sony FE 50mm F1.4 GM",
                [32880] = "Sony FE 16mm F1.8 G",
                [32881] = "Sony FE 24-50mm F2.8 G",
                [32882] = "Sony FE 16-25mm F2.8 G",
                [32884] = "Sony FE 70-200mm F4 Macro G OSS II",
                [32885] = "Sony FE 16-35mm F2.8 GM II",
                [32886] = "Sony FE 300mm F2.8 GM OSS",
                [32887] = "Sony E PZ 16-50mm F3.5-5.6 OSS II",
                [32888] = "Sony FE 85mm F1.4 GM II",
                [32889] = "Sony FE 28-70mm F2 GM",
                [32890] = "Sony FE 400-800mm F6.3-8 G OSS",
                [32891] = "Sony FE 50-150mm F2 GM",
                [32893] = "Sony FE 100mm F2.8 Macro GM OSS",
                [33072] = "Sony FE 70-200mm F2.8 GM OSS + 1.4X Teleconverter",
                [33073] = "Sony FE 70-200mm F2.8 GM OSS + 2X Teleconverter",
                [33076] = "Sony FE 100mm F2.8 STF GM OSS (macro mode)",
                [33077] = "Sony FE 100-400mm F4.5-5.6 GM OSS + 1.4X Teleconverter",
                [33078] = "Sony FE 100-400mm F4.5-5.6 GM OSS + 2X Teleconverter",
                [33079] = "Sony FE 400mm F2.8 GM OSS + 1.4X Teleconverter",
                [33080] = "Sony FE 400mm F2.8 GM OSS + 2X Teleconverter",
                [33081] = "Sony FE 200-600mm F5.6-6.3 G OSS + 1.4X Teleconverter",
                [33082] = "Sony FE 200-600mm F5.6-6.3 G OSS + 2X Teleconverter",
                [33083] = "Sony FE 600mm F4 GM OSS + 1.4X Teleconverter",
                [33084] = "Sony FE 600mm F4 GM OSS + 2X Teleconverter",
                [33085] = "Sony FE 70-200mm F2.8 GM OSS II + 1.4X Teleconverter",
                [33086] = "Sony FE 70-200mm F2.8 GM OSS II + 2X Teleconverter",
                [33087] = "Sony FE 70-200mm F4 Macro G OSS II + 1.4X Teleconverter",
                [33088] = "Sony FE 70-200mm F4 Macro G OSS II + 2X Teleconverter",
                [33089] = "Sony FE 300mm F2.8 GM OSS + 1.4X Teleconverter",
                [33090] = "Sony FE 300mm F2.8 GM OSS + 2X Teleconverter",
                [33091] = "Sony FE 400-800mm F6.3-8 G OSS + 1.4X Teleconverter",
                [33092] = "Sony FE 400-800mm F6.3-8 G OSS + 2X Teleconverter",
                [33093] = "Sony FE 100mm F2.8 Macro GM OSS + 1.4X Teleconverter",
                [33094] = "Sony FE 100mm F2.8 Macro GM OSS + 2X Teleconverter",
                [49201] = "Zeiss Touit 12mm F2.8 or other Touit lens",
                [49202] = "Zeiss Touit 32mm F1.8",
                [49203] = "Zeiss Touit 50mm F2.8 Macro",
                [49216] = "Zeiss Batis 25mm F2",
                [49217] = "Zeiss Batis 85mm F1.8",
                [49218] = "Zeiss Batis 18mm F2.8",
                [49219] = "Zeiss Batis 135mm F2.8",
                [49220] = "Zeiss Batis 40mm F2 CF",
                [49232] = "Zeiss Loxia 50mm F2",
                [49233] = "Zeiss Loxia 35mm F2",
                [49234] = "Zeiss Loxia 21mm F2.8",
                [49235] = "Zeiss Loxia 85mm F2.4",
                [49236] = "Zeiss Loxia 25mm F2.4",
                [49456] = "Tamron E 18-200mm F3.5-6.3 Di III VC",
                [49457] = "Tamron 28-75mm F2.8 Di III RXD",
                [49458] = "Tamron 17-28mm F2.8 Di III RXD",
                [49459] = "Tamron 35mm F2.8 Di III OSD M1:2",
                [49460] = "Tamron 24mm F2.8 Di III OSD M1:2",
                [49461] = "Tamron 20mm F2.8 Di III OSD M1:2",
                [49462] = "Tamron 70-180mm F2.8 Di III VXD",
                [49463] = "Tamron 28-200mm F2.8-5.6 Di III RXD",
                [49464] = "Tamron 70-300mm F4.5-6.3 Di III RXD",
                [49465] = "Tamron 17-70mm F2.8 Di III-A VC RXD",
                [49466] = "Tamron 150-500mm F5-6.7 Di III VC VXD",
                [49467] = "Tamron 11-20mm F2.8 Di III-A RXD",
                [49468] = "Tamron 18-300mm F3.5-6.3 Di III-A VC VXD",
                [49469] = "Tamron 35-150mm F2-F2.8 Di III VXD",
                [49470] = "Tamron 28-75mm F2.8 Di III VXD G2",
                [49471] = "Tamron 50-400mm F4.5-6.3 Di III VC VXD",
                [49472] = "Tamron 20-40mm F2.8 Di III VXD",
                [49473] = "Tamron 17-50mm F4 Di III VXD or Tokina or Viltrox lens",
                [49474] = "Tamron 70-180mm F2.8 Di III VXD G2 or Viltrox lens",
                [49475] = "Tamron 50-300mm F4.5-6.3 Di III VC VXD",
                [49476] = "Tamron 28-300mm F4-7.1 Di III VC VXD",
                [49477] = "Tamron 90mm F2.8 Di III Macro VXD",
                [49478] = "Tamron 16-30mm F2.8 Di III VXD G2",
                [49479] = "Tamron 25-200mm F2.8-5.6 Di III VXD G2",
                [49480] = "Tamron 35-100mm F2.8 Di III VXD",
                [49712] = "Tokina FiRIN 20mm F2 FE AF",
                [49713] = "Tokina FiRIN 100mm F2.8 FE MACRO",
                [49714] = "Tokina atx-m 11-18mm F2.8 E",
                [50480] = "Sigma 30mm F1.4 DC DN | C",
                [50481] = "Sigma 50mm F1.4 DG HSM | A",
                [50482] = "Sigma 18-300mm F3.5-6.3 DC MACRO OS HSM | C + MC-11",
                [50483] = "Sigma 18-35mm F1.8 DC HSM | A + MC-11",
                [50484] = "Sigma 24-35mm F2 DG HSM | A + MC-11",
                [50485] = "Sigma 24mm F1.4 DG HSM | A + MC-11",
                [50486] = "Sigma 150-600mm F5-6.3 DG OS HSM | C + MC-11",
                [50487] = "Sigma 20mm F1.4 DG HSM | A + MC-11",
                [50488] = "Sigma 35mm F1.4 DG HSM | A",
                [50489] = "Sigma 150-600mm F5-6.3 DG OS HSM | S + MC-11",
                [50490] = "Sigma 120-300mm F2.8 DG OS HSM | S + MC-11",
                [50492] = "Sigma 24-105mm F4 DG OS HSM | A + MC-11",
                [50493] = "Sigma 17-70mm F2.8-4 DC MACRO OS HSM | C + MC-11",
                [50495] = "Sigma 50-100mm F1.8 DC HSM | A + MC-11",
                [50499] = "Sigma 85mm F1.4 DG HSM | A",
                [50501] = "Sigma 100-400mm F5-6.3 DG OS HSM | C + MC-11",
                [50503] = "Sigma 16mm F1.4 DC DN | C",
                [50507] = "Sigma 105mm F1.4 DG HSM | A",
                [50508] = "Sigma 56mm F1.4 DC DN | C",
                [50512] = "Sigma 70-200mm F2.8 DG OS HSM | S + MC-11",
                [50513] = "Sigma 70mm F2.8 DG MACRO | A",
                [50514] = "Sigma 45mm F2.8 DG DN | C",
                [50515] = "Sigma 35mm F1.2 DG DN | A",
                [50516] = "Sigma 14-24mm F2.8 DG DN | A",
                [50517] = "Sigma 24-70mm F2.8 DG DN | A",
                [50518] = "Sigma 100-400mm F5-6.3 DG DN OS | C",
                [50521] = "Sigma 85mm F1.4 DG DN | A",
                [50522] = "Sigma 105mm F2.8 DG DN MACRO | A",
                [50523] = "Sigma 65mm F2 DG DN | C",
                [50524] = "Sigma 35mm F2 DG DN | C",
                [50525] = "Sigma 24mm F3.5 DG DN | C",
                [50526] = "Sigma 28-70mm F2.8 DG DN | C",
                [50527] = "Sigma 150-600mm F5-6.3 DG DN OS | S",
                [50528] = "Sigma 35mm F1.4 DG DN | A",
                [50529] = "Sigma 90mm F2.8 DG DN | C",
                [50530] = "Sigma 24mm F2 DG DN | C",
                [50531] = "Sigma 18-50mm F2.8 DC DN | C",
                [50532] = "Sigma 20mm F2 DG DN | C",
                [50533] = "Sigma 16-28mm F2.8 DG DN | C",
                [50534] = "Sigma 20mm F1.4 DG DN | A",
                [50535] = "Sigma 24mm F1.4 DG DN | A",
                [50536] = "Sigma 60-600mm F4.5-6.3 DG DN OS | S",
                [50537] = "Sigma 50mm F2 DG DN | C",
                [50538] = "Sigma 17mm F4 DG DN | C",
                [50539] = "Sigma 50mm F1.4 DG DN | A",
                [50540] = "Sigma 14mm F1.4 DG DN | A",
                [50543] = "Sigma 70-200mm F2.8 DG DN OS | S",
                [50544] = "Sigma 23mm F1.4 DC DN | C",
                [50545] = "Sigma 24-70mm F2.8 DG DN II | A",
                [50546] = "Sigma 500mm F5.6 DG DN OS | S",
                [50547] = "Sigma 10-18mm F2.8 DC DN | C",
                [50548] = "Sigma 15mm F1.4 DG DN DIAGONAL FISHEYE | A",
                [50549] = "Sigma 50mm F1.2 DG DN | A",
                [50550] = "Sigma 28-105mm F2.8 DG DN | A",
                [50551] = "Sigma 28-45mm F1.8 DG DN | A",
                [50552] = "Sigma 35mm F1.2 DG II | A",
                [50553] = "Sigma 300-600mm F4 DG OS | S",
                [50554] = "Sigma 16-300mm F3.5-6.7 DC OS | C",
                [50555] = "Sigma 12mm F1.4 DC | C",
                [50556] = "Sigma 17-40mm F1.8 DC | A",
                [50557] = "Sigma 200mm F2 DG OS | S",
                [50558] = "Sigma 20-200mm F3.5-6.3 DG | C",
                [50559] = "Sigma 135mm F1.4 DG | A",
                [50992] = "Voigtlander SUPER WIDE-HELIAR 15mm F4.5 III",
                [50993] = "Voigtlander HELIAR-HYPER WIDE 10mm F5.6",
                [50994] = "Voigtlander ULTRA WIDE-HELIAR 12mm F5.6 III",
                [50995] = "Voigtlander MACRO APO-LANTHAR 65mm F2 Aspherical",
                [50996] = "Voigtlander NOKTON 40mm F1.2 Aspherical",
                [50997] = "Voigtlander NOKTON classic 35mm F1.4",
                [50998] = "Voigtlander MACRO APO-LANTHAR 110mm F2.5",
                [50999] = "Voigtlander COLOR-SKOPAR 21mm F3.5 Aspherical",
                [51000] = "Voigtlander NOKTON 50mm F1.2 Aspherical",
                [51001] = "Voigtlander NOKTON 21mm F1.4 Aspherical",
                [51002] = "Voigtlander APO-LANTHAR 50mm F2 Aspherical",
                [51003] = "Voigtlander NOKTON 35mm F1.2 Aspherical SE",
                [51006] = "Voigtlander APO-LANTHAR 35mm F2 Aspherical",
                [51007] = "Voigtlander NOKTON 50mm F1 Aspherical",
                [51008] = "Voigtlander NOKTON 75mm F1.5 Aspherical",
                [51009] = "Voigtlander NOKTON 28mm F1.5 Aspherical",
                [51072] = "ZEISS Otus ML 50mm F1.4",
                [51073] = "ZEISS Otus ML 85mm F1.4",
                [51504] = "Samyang AF 50mm F1.4",
                [51505] = "Samyang AF 14mm F2.8 or Samyang AF 35mm F2.8",
                [51507] = "Samyang AF 35mm F1.4",
                [51508] = "Samyang AF 45mm F1.8",
                [51510] = "Samyang AF 18mm F2.8 or Samyang AF 35mm F1.8",
                [51512] = "Samyang AF 75mm F1.8",
                [51513] = "Samyang AF 35mm F1.8",
                [51514] = "Samyang AF 24mm F1.8",
                [51515] = "Samyang AF 12mm F2.0",
                [51516] = "Samyang AF 24-70mm F2.8",
                [51517] = "Samyang AF 50mm F1.4 II",
                [51518] = "Samyang AF 135mm F1.8",
                [61569] = "LAOWA FFII 10mm F2.8 C&D Dreamer",
                [61572] = "LAOWA FFII 12mm F2.8 C&D Dreamer",
                [61760] = "Viltrox 135mm F1.8 FE LAB",
                [61761] = "Viltrox 28mm F4.5 FE",
                [61762] = "Viltrox 35mm F1.2 FE LAB",
                [61763] = "Viltrox 85mm F1.4 FE PRO",
                [61767] = "Viltrox 50mm F2.0 FE AIR",
                [61776] = "Viltrox 50mm F1.4 FE PRO",
                [61780] = "Viltrox 85mm F2.0 FE EVO",
    };

    private static readonly Dictionary<int, string> _pc6 = new()
    {
                [0] = "16:9",
                [1] = "4:3",
                [2] = "3:2",
                [3] = "1:1",
                [5] = "Panorama",
    };

    private static readonly Dictionary<int, string> _pc7 = new()
    {
                [0] = "Standard (PP2)",
                [1] = "Portrait",
                [3] = "Night View",
                [4] = "B&W/Sepia",
                [5] = "Clear",
                [6] = "Deep",
                [7] = "Light",
                [8] = "Vivid",
                [9] = "Real",
                [10] = "Movie (PP1)",
                [22] = "ITU709 (PP3/PP4)",
                [24] = "Cine1 (PP5)",
                [25] = "Cine2 (PP6)",
                [26] = "Cine3",
                [27] = "Cine4",
                [28] = "S-Log2 (PP7)",
                [29] = "ITU709 (800%)",
                [31] = "S-Log3 (PP8/PP9)",
                [33] = "HLG2 (PP10)",
                [34] = "HLG3",
                [36] = "Off",
                [37] = "FL",
                [38] = "VV2",
                [39] = "IN",
                [40] = "SH",
                [48] = "FL2",
                [49] = "FL3",
    };

    private static readonly Dictionary<int, string> _pc8 = new()
    {
                [0] = "Unknown",
                [1] = "APS-C",
                [2] = "Full-frame",
    };

    private static readonly Dictionary<int, string> _pc9 = new()
    {
                [0] = "0",
                [33] = "5",
                [57] = "2",
                [77] = "4",
                [93] = "3",
                [98] = "1",
                [115] = "8",
                [168] = "6",
                [241] = "7",
    };

    // ─── 子表字段定义 ────────────────────────────────────────────────

    /// <summary>
    /// 子表字段定义。
    /// Key = 子表名称, Value = (偏移量, 字段名, 格式, PrintConv引用, 值公式) 列表
    /// </summary>
    private static readonly Dictionary<string, (int Offset, string Name, FieldFormat Format, Dictionary<int, string>? PrintConv, ValueFormula Formula)[]> FieldDefs = new()
    {
        ["AFInfo"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0002, "AFType", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0004, "AFStatusActiveSensor", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0005, "FocusMode", FieldFormat.Int8u, _pc1, ValueFormula.None),
            (0x000A, "AFAreaMode", FieldFormat.Int8u, _pc0, ValueFormula.None),
            (0x0010, "AFPointsUsed", FieldFormat.Int8u, _pc2, ValueFormula.None),
            (0x0037, "AFPoint", FieldFormat.Int8u, _pc3, ValueFormula.None),
            (0x003A, "AFAreaMode", FieldFormat.Int8u, _pc4, ValueFormula.None),
            (0x003B, "AFStatusActiveSensor", FieldFormat.Int8u, null, ValueFormula.None),
            (0x017E, "ExposureProgram", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag2010b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0000, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x1A23, "DistortionCorrParams", FieldFormat.Int16s, null, ValueFormula.None),
        },
        ["Tag2010c"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0000, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
        },
        ["Tag2010d"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0000, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
        },
        ["Tag2010e"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0000, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x1870, "DistortionCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1891, "LensFormat", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1892, "LensMount", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1893, "LensType2", FieldFormat.Int16u, _pc5, ValueFormula.None),
            (0x1898, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1899, "DistortionCorrParamsNumber", FieldFormat.Int8u, null, ValueFormula.None),
            (0x192C, "AspectRatio", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1A88, "AspectRatio", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag2010f"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x1136, "MinFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x1138, "MaxFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x113C, "SonyISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x192C, "AspectRatio", FieldFormat.Int16u, _pc6, ValueFormula.None),
        },
        ["Tag2010g"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0004, "WB_RGBLevels", FieldFormat.Int32u, null, ValueFormula.Divide10),
            (0x0237, "PictureProfile", FieldFormat.Int8u, _pc7, ValueFormula.None),
            (0x032E, "MinFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0330, "MaxFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0344, "SonyISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x18C4, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1958, "AspectRatio", FieldFormat.Int16u, _pc6, ValueFormula.None),
        },
        ["Tag2010h"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0004, "WB_RGBLevels", FieldFormat.Int32u, null, ValueFormula.Divide10),
            (0x032E, "MinFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0330, "MaxFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0346, "SonyISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x0388, "MeterInfo", FieldFormat.Int32u, null, ValueFormula.None),
            (0x0398, "MeterInfo", FieldFormat.Int32u, null, ValueFormula.None),
            (0x18CC, "DistortionCorrParams", FieldFormat.Int16s, _pc8, ValueFormula.None),
            (0x18F4, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x192C, "AspectRatio", FieldFormat.Int16u, _pc6, ValueFormula.None),
        },
        ["Tag2010i"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0004, "WB_RGBLevels", FieldFormat.Int32u, null, ValueFormula.Divide10),
            (0x030C, "MinFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x030E, "MaxFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0320, "SonyISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x17F8, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x188C, "AspectRatio", FieldFormat.Int8u, _pc6, ValueFormula.None),
        },
        ["Tag900b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0002, "FacesDetected", FieldFormat.Int8u, _pc9, ValueFormula.None),
        },
        ["Tag9050a"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0020, "Shutter", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x0031, "FlashStatus", FieldFormat.Int8u, _pc10, ValueFormula.None),
            (0x003C, "SonyFNumber", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x003F, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x004C, "ShutterCount2", FieldFormat.Int32u, null, ValueFormula.Mask24bit),
            (0x0067, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x007C, "InternalSerialNumber", FieldFormat.Int8u, null, ValueFormula.None),
            (0x00F0, "InternalSerialNumber", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0105, "LensMount", FieldFormat.Int16u, _pc11, ValueFormula.None),
            (0x010B, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0115, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0116, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
            (0x01A0, "ShutterCount3", FieldFormat.Int32u, null, ValueFormula.None),
            (0x01AA, "ShutterCount3", FieldFormat.Int32u, null, ValueFormula.None),
            (0x01BD, "ShutterCount3", FieldFormat.Int32u, null, ValueFormula.None),
        },
        ["Tag9050b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0026, "Shutter", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x0039, "FlashStatus", FieldFormat.Int8u, _pc10, ValueFormula.None),
            (0x003A, "ShutterCount", FieldFormat.Int32u, null, ValueFormula.Mask24bit),
            (0x0046, "SonyExposureTime", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x0048, "SonyFNumber", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x004B, "ReleaseMode2", FieldFormat.Int8u, _pc12, ValueFormula.None),
            (0x0052, "ShutterCount2", FieldFormat.Int32u, null, ValueFormula.Mask24bit),
            (0x0058, "ShutterCount2", FieldFormat.Int32u, null, ValueFormula.Mask24bit),
            (0x0061, "SonyTimeMinSec", FieldFormat.Int8u, null, ValueFormula.None),
            (0x006B, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x006D, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0073, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0088, "InternalSerialNumber", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0105, "LensMount", FieldFormat.Int8u, _pc11, ValueFormula.None),
            (0x0106, "LensFormat", FieldFormat.Int8u, _pc8, ValueFormula.None),
            (0x010B, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0114, "APS-CSizeCapture", FieldFormat.Int8u, _pc13, ValueFormula.None),
            (0x0116, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
            (0x019F, "ShutterCount3", FieldFormat.Int32u, null, ValueFormula.None),
            (0x01CB, "ShutterCount3", FieldFormat.Int32u, null, ValueFormula.None),
            (0x01CD, "ShutterCount3", FieldFormat.Int32u, null, ValueFormula.None),
            (0x01ED, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
            (0x01F0, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
            (0x021C, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
            (0x021E, "LensSpecFeatures", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9050c"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0026, "Shutter", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x0039, "FlashStatus", FieldFormat.Int8u, _pc10, ValueFormula.None),
            (0x0048, "SonyFNumber", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x004B, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0066, "SonyExposureTime", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x0068, "SonyFNumber", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x006B, "ReleaseMode2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x008A, "InternalSerialNumber", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9050d"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x000A, "ShutterCount", FieldFormat.Int32u, null, ValueFormula.Mask24bit),
            (0x001A, "SonyExposureTime", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x001C, "SonyFNumber", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x001F, "ReleaseMode2", FieldFormat.Int8u, _pc12, ValueFormula.None),
        },
        ["Tag9400a"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0008, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x001A, "ShotNumberSincePowerUp", FieldFormat.Int32u, null, ValueFormula.None),
            (0x0022, "SequenceLength", FieldFormat.Int8u, _pc14, ValueFormula.None),
            (0x0028, "CameraOrientation", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0029, "Quality2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0052, "ModelReleaseYear", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9400b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0008, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x0025, "Quality2", FieldFormat.Int8u, _pc15, ValueFormula.None),
            (0x003F, "SonyImageHeight", FieldFormat.Int16u, null, ValueFormula.None),
        },
        ["Tag9400c"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0009, "ReleaseMode2", FieldFormat.Int8u, _pc16, ValueFormula.None),
            (0x0012, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x0029, "CameraOrientation", FieldFormat.Int8u, _pc17, ValueFormula.None),
            (0x002A, "Quality2", FieldFormat.Int8u, _pc18, ValueFormula.None),
            (0x0053, "ModelReleaseYear", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0133, "ShutterType", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0139, "ShutterType", FieldFormat.Int8u, null, ValueFormula.None),
            (0x013F, "ShutterType", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9401"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0000, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x044E, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x049E, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x04A1, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x04A2, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x04BA, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x0634, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x064C, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x06B8, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x06DE, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
            (0x06E7, "_ISOInfo_", FieldFormat.Int8u, null, ValueFormula.ISOInfo),
        },
        ["Tag9402"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0002, "TempTest1", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0004, "FocusMode", FieldFormat.Int8u, _pc19, ValueFormula.Mask0x7F),
            (0x0016, "FocusMode", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0017, "AFAreaMode", FieldFormat.Int8u, _pc20, ValueFormula.None),
        },
        ["Tag9403"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0004, "TempTest2", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9404a"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x000B, "ExposureProgram", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9404b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x000C, "ExposureProgram", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9404c"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x000B, "ExposureProgram", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9405a"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0600, "DistortionCorrParamsPresent", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0601, "DistortionCorrection", FieldFormat.Int8u, _pc21, ValueFormula.None),
            (0x0604, "LensMount", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0605, "LensType2", FieldFormat.Int16u, _pc5, ValueFormula.None),
            (0x066A, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x06CA, "DistortionCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9405b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0004, "SonyISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x0006, "BaseISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x000A, "StopsAboveBaseISO", FieldFormat.Int16u, null, ValueFormula.Divide256),
            (0x0010, "ExposureTime", FieldFormat.Rational32u, null, ValueFormula.None),
            (0x0014, "SonyFNumber", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x0016, "SonyMaxApertureValue", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x0024, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x0042, "HighISONoiseReduction", FieldFormat.Int8u, _pc22, ValueFormula.None),
            (0x0044, "LongExposureNoiseReduction", FieldFormat.Int8u, _pc13, ValueFormula.None),
            (0x0046, "PictureEffect2", FieldFormat.Int8u, _pc23, ValueFormula.None),
            (0x0048, "ExposureProgram", FieldFormat.Int8u, _pc24, ValueFormula.None),
            (0x004A, "CreativeStyle", FieldFormat.Int8u, _pc25, ValueFormula.None),
            (0x005D, "LensFormat", FieldFormat.Int8u, _pc8, ValueFormula.None),
            (0x005E, "LensMount", FieldFormat.Int8u, _pc11, ValueFormula.None),
            (0x034A, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x034E, "LensZoomPosition", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0350, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x035A, "LensZoomPosition", FieldFormat.Int8u, null, ValueFormula.None),
            (0x035C, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0368, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x037C, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0384, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x039C, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x03B0, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x03B8, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9406"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0005, "BatteryTemperature", FieldFormat.Int8u, null, ValueFormula.BatteryTemp),
            (0x0006, "BatteryLevelGrip1", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0007, "BatteryLevel", FieldFormat.Int8u, null, ValueFormula.Percentage),
            (0x0008, "BatteryLevelGrip2", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9406b"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0001, "Battery2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0005, "BatteryLevel", FieldFormat.Int8u, null, ValueFormula.Percentage),
            (0x0007, "BatteryLevel2", FieldFormat.Int8u, null, ValueFormula.Percentage),
        },
        ["Tag940a"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0004, "AFPointsSelected", FieldFormat.Int32u, _pc2, ValueFormula.None),
        },
        ["Tag940c"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0008, "LensMount2", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0009, "LensType3", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0014, "LensFirmwareVersion", FieldFormat.Int16u, null, ValueFormula.None),
        },
        ["Tag940e"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x1A06, "TiffMeteringImageWidth", FieldFormat.Int8u, null, ValueFormula.None),
            (0x1A07, "TiffMeteringImageHeight", FieldFormat.Int8u, null, ValueFormula.None),
        },
        ["Tag9416"] = new (int, string, FieldFormat, Dictionary<int, string>?, ValueFormula)[]
        {
            (0x0000, "Tag9416_0000", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0004, "SonyISO", FieldFormat.Int16u, null, ValueFormula.SonyISO),
            (0x0006, "SonyExposureTime2", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x000A, "SonyExposureTime2", FieldFormat.Int16u, null, ValueFormula.ExposureTime16),
            (0x000C, "ExposureTime", FieldFormat.Rational32u, null, ValueFormula.None),
            (0x0010, "SonyFNumber2", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x0012, "SonyMaxApertureValue", FieldFormat.Int16u, null, ValueFormula.SonyFNumber),
            (0x001D, "SequenceImageNumber", FieldFormat.Int32u, null, ValueFormula.None),
            (0x0035, "ExposureProgram", FieldFormat.Int8u, _pc24, ValueFormula.None),
            (0x0048, "LensMount", FieldFormat.Int8u, _pc11, ValueFormula.None),
            (0x0049, "LensFormat", FieldFormat.Int8u, _pc8, ValueFormula.None),
            (0x004A, "LensMount", FieldFormat.Int8u, _pc11, ValueFormula.None),
            (0x004B, "LensType2", FieldFormat.Int16u, _pc5, ValueFormula.None),
            (0x004F, "DistortionCorrParams", FieldFormat.Int16s, null, ValueFormula.Divide10),
            (0x0073, "MinFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0075, "MaxFocalLength", FieldFormat.Int16u, null, ValueFormula.Divide10),
            (0x0702, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x083B, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x088F, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0891, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x089D, "VignettingCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0914, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0916, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
            (0x0945, "ChromaticAberrationCorrParams", FieldFormat.Int8u, null, ValueFormula.None),
        },
    };
}
