#!/usr/bin/env python3
"""
Tools/generate-exiftool-tags.py

从 ExifTool Perl 源码自动生成 MetadataExtractor 补充 tag 名称映射 C# 文件。
每次想跟进 ExifTool 新版本时，重新运行此脚本即可。

用法:
    python3 Tools/generate-exiftool-tags.py [--ref <git-ref>]

参数:
    --ref   ExifTool GitHub 仓库的 git ref（分支/tag/commit），默认 master

输出:
    PhotoViewer/Core/ExifToolTags.Generated.cs
"""

import re
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path
from argparse import ArgumentParser
from typing import Optional

EXIFTOOL_RAW = "https://raw.githubusercontent.com/exiftool/exiftool/{ref}/lib/Image/ExifTool/{file}.pm"

# (C# 模块键名, ExifTool .pm 文件名（不含后缀）)
MODULES: list[tuple[str, str]] = [
    ("Sony",      "Sony"),
    ("Nikon",     "Nikon"),
    ("Canon",     "Canon"),
    ("Fujifilm",  "FujiFilm"),
    ("Panasonic", "Panasonic"),
    ("Olympus",   "Olympus"),
    ("Pentax",    "Pentax"),
    ("Sigma",     "Sigma"),
    ("Minolta",   "Minolta"),
    ("Samsung",   "Samsung"),
    ("Apple",     "Apple"),
    ("Reconyx",   "Reconyx"),
    ("Ricoh",     "Ricoh"),
    ("Casio",     "Casio"),
    ("Kodak",     "Kodak"),
    ("DJI",       "DJI"),
    ("Kyocera",   "KyoceraRaw"),
    ("Sanyo",     "Sanyo"),
    ("FLIR",      "FLIR"),
]

REPO_ROOT = Path(__file__).parent.parent
OUTPUT_PATH = REPO_ROOT / "PhotoViewer" / "Core" / "ExifToolTags.Generated.cs"

# 匹配 tag ID 行: 以缩进开头，后跟十六进制 0xHEX 或短十进制（最多 5 位），再跟 =>
_TAG_ID_RE = re.compile(r'^\s+(0x[0-9a-fA-F]{1,6}|\b\d{1,5}\b)\s*=>')
# 匹配 Name => 'TagName' 或 Name => "TagName"（仅允许合法标识符名）
_NAME_RE = re.compile(r'Name\s*=>\s*[\'"]([A-Za-z][A-Za-z0-9_]{1,80})[\'"]')
# 匹配行尾直接跟字符串字面量的 tag 命名格式: => 'TagName',
_INLINE_STR_RE = re.compile(r"^['\"]([A-Za-z][A-Za-z0-9_]{1,80})['\"]")


def fetch_pm(file_name: str, ref: str) -> Optional[str]:
    url = EXIFTOOL_RAW.format(ref=ref, file=file_name)
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        print(f"[SKIP] HTTP {e.code}: {file_name}.pm", file=sys.stderr)
        return None
    except Exception as e:
        print(f"[ERROR] {file_name}.pm: {e}", file=sys.stderr)
        return None


def extract_tags(content: str) -> "dict[int, str]":
    """
    从 ExifTool .pm 文件内容提取 tagId -> tagName 映射（合并文件内所有哈希表）。

    支持两种格式：
      格式1: 0xHEX => { Name => 'TagName', ... }
      格式2: 0xHEX => 'TagName',
    """
    tags = {}  # type: dict[int, str]
    lines = content.split('\n')
    n = len(lines)

    for i, line in enumerate(lines):
        m = _TAG_ID_RE.match(line)
        if not m:
            continue

        raw_id = m.group(1)
        try:
            tag_id = int(raw_id, 16) if raw_id.lower().startswith('0x') else int(raw_id)
        except ValueError:
            continue

        rest = line[m.end():].strip()

        # 格式2: => 'TagName'（直接内联字符串）
        sm = _INLINE_STR_RE.match(rest)
        if sm:
            tags[tag_id] = sm.group(1)
            continue

        # 格式1: => { ... Name => 'TagName' ... }
        if rest.startswith('{'):
            for j in range(i + 1, min(i + 25, n)):
                nm = _NAME_RE.search(lines[j])
                if nm:
                    tags[tag_id] = nm.group(1)
                    break
                # 遇到下一个顶层 tag ID 则停止向前扫描
                if _TAG_ID_RE.match(lines[j]):
                    break

    return tags


def _cs_hex(tag_id: int) -> str:
    """将 tag ID 格式化为 C# 十六进制字面量，根据大小选择位数。"""
    if tag_id <= 0xFFFF:
        return f"0x{tag_id:04x}"
    return f"0x{tag_id:08x}"


def _escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def generate_cs(module_tags: "list[tuple[str, dict[int, str]]]", ref: str) -> str:
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    total = sum(len(t) for _, t in module_tags)

    out: list[str] = [
        "// <auto-generated>",
        "// 由 Tools/generate-exiftool-tags.py 从 ExifTool Perl 源码自动生成。",
        f"// ExifTool git ref : {ref}",
        f"// 生成时间         : {now}",
        f"// 模块数           : {len(module_tags)}  Tag 总数: {total}",
        "// 请勿手动编辑，运行脚本以同步最新版本。",
        "// </auto-generated>",
        "",
        "using System.Collections.Generic;",
        "",
        "namespace PhotoViewer.Core;",
        "",
        "internal static partial class ExifToolTags",
        "{",
        "    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<int, string>> _tables =",
        "        new Dictionary<string, IReadOnlyDictionary<int, string>>",
        "        {",
    ]

    for module_name, tags in module_tags:
        if not tags:
            continue
        out.append(f'            ["{_escape(module_name)}"] = new Dictionary<int, string>')
        out.append("            {")
        for tag_id, tag_name in sorted(tags.items()):
            out.append(f'                [{_cs_hex(tag_id)}] = "{_escape(tag_name)}",')
        out.append("            },")

    out += [
        "        };",
        "}",
        "",
    ]
    return '\n'.join(out)


def main() -> None:
    parser = ArgumentParser(description="从 ExifTool Perl 源码生成 C# tag 名称补充映射文件")
    parser.add_argument('--ref', default='master',
                        help='ExifTool GitHub 仓库的 git ref（默认: master）')
    args = parser.parse_args()
    ref = args.ref  # type: str

    print(f"ExifTool ref: {ref}")
    print(f"输出路径: {OUTPUT_PATH.relative_to(REPO_ROOT)}\n")

    module_tags = []  # type: list[tuple[str, dict[int, str]]]
    for module_name, file_name in MODULES:
        print(f"  Fetching {file_name}.pm ...", end=' ', flush=True)
        content = fetch_pm(file_name, ref)
        if content is None:
            continue
        tags = extract_tags(content)
        module_tags.append((module_name, tags))
        print(f"{len(tags)} tags")

    cs_content = generate_cs(module_tags, ref)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(cs_content, encoding='utf-8')

    total = sum(len(t) for _, t in module_tags)
    print(f"\n✓ 生成完成，共 {len(module_tags)} 个模块，{total} 条 tag 记录")


if __name__ == '__main__':
    main()
